data:
  root: /kaggle/input
  scene_list: [sample_plant_001]
  use_depth: false
grid:
  type: sparse_octree
  base_res: 64
  max_res: 128
dino:
  pretrained: "vit_base_patch16_224.dino"
  freeze: true
renderer:
  n_samples: 64
loss:
  lambda_sil: 1.0
  lambda_depth: 0.0
  lambda_geom: 0.5
  lambda_dino: 0.1
train:
  epochs: 2
  batch_size: 1
  lr: 2.0e-4
  amp: true
paths:
  out_root: /kaggle/working/outputs
